---
kind: List
apiVersion: v1beta1
items:
##
# Put external postgres configuration here, if you have one.
##
- apiVersion: apps/v1beta1
  kind: Deployment
  metadata:
    name: jobrunner
  spec:
    replicas: 1
    template:
      metadata:
        name: jobrunner
        labels:
          app: jobrunner
          tier: jobrunner
      spec:
        containers:
        - image: blackducksoftware/hub-jobrunner:4.2.1
          resources:
            requests:
              cpu: 1
              memory: 4608M
            limits:
              cpu: 1
              memory: 4608M
          name: jobrunner
          envFrom:
          - configMapRef:
              name: hub-config

- apiVersion: apps/v1beta1
  kind: Deployment
  metadata:
    name: nginx-webapp-logstash
  spec:
    replicas: 1
    template:
      metadata:
        name: nginx-webapp-logstash
        labels:
          app: nginx-webapp-logstash
          tier: nginx-webapp-logstash
      spec:
        volumes:
        - emptyDir: {}
          name: dir-webapp
        - emptyDir: {}
          name: dir-logstash
        - name: dir-webserver
          emptyDir: {}
# uncomment the below lines if you want to customize hub logging with a config map
#        - name: dir-logstash-conf
#          configMap:
#            name: hub-logstash-conf
#            items:
#            - key: logstash.conf
#              path: logstash.conf
        containers:
        - name: webapp
          resources:
            requests:
              cpu: 1
              memory: 4608M
            limits:
              cpu: 1
              memory: 4608M
          image: blackducksoftware/hub-webapp:4.2.1
          envFrom:
          - configMapRef:
              name: hub-config
          env:
          volumeMounts:
          - mountPath: "/opt/blackduck/hub/logs"
            name: dir-webapp
          - mountPath: "/var/lib/logstash/data"
            name: dir-logstash
          ports:
          - containerPort: 8080
        - image: blackducksoftware/hub-logstash:4.2.1
          name: logstash
          resources:
            requests:
              memory: 640M
            limits:
              memory: 640M
          volumeMounts:
          - mountPath: "/opt/blackduck/hub/logs"
            name: dir-webapp
          - mountPath: "/var/lib/logstash/data"
            name: dir-logstash
          ports:
          - containerPort: 4560
            containerPort: 5044 # filebeat
# uncomment the below lines if you want to customize the file path for logstash via a config map mount.
#          cmd: ["/docker-entrypoint.sh"]
#          args: ["-f", "/var/hub-config/logstash.conf"]
        - name: nginx
          resources:
            requests:
              memory: 512M
            limits:
              memory: 512M
          image: blackducksoftware/hub-nginx:4.2.1
          ports:
          - containerPort: 8443
          volumes:
            volumeMounts:
            - mountPath: "/opt/blackduck/hub/webserver/security"
              name: dir-webserver
- apiVersion: apps/v1beta1
  kind: Deployment
  metadata:
    name: documentation
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: documentation
        name: documentation
      spec:
        containers:
        - image: "blackducksoftware/hub-documentation:4.2.1"
          name: documentation
          resources:
            limits:
              memory: "512M"
            requests:
              memory: "512M"
          ports:
          - containerPort: 8080
- apiVersion: apps/v1beta1
  kind: Deployment
  metadata:
    name: solr
  spec:
    replicas: 1
    template:
      metadata:
        name: solr
        labels:
          app: solr
          tier: solr
      spec:
        containers:
        - name: solr
          resources:
            requests:
              memory: "640M"
            limits:
              memory: "640M"
          image: blackducksoftware/hub-solr:4.2.1
          envFrom:
          - configMapRef:
              name: hub-config

- apiVersion: apps/v1beta1
  kind: Deployment
  metadata:
    name: registration
  spec:
    replicas: 1
    template:
      metadata:
        name: registration
        labels:
          app: registration
          tier: registration
      spec:
        containers:
        - envFrom:
          - configMapRef:
              name: hub-config
          image: blackducksoftware/hub-registration:4.2.1
          name: registration
          ports:
          - containerPort: 8080
          volumes:
          - emptyDir: {}
            name: dir-1
            volumeMounts:
            - mountPath: "/opt/blackduck/hub/registration/config"
              name: dir-1
- apiVersion: apps/v1beta1
  kind: Deployment
  metadata:
    name: zookeeper
  spec:
    replicas: 1
    template:
      metadata:
        name: zookeeper
        labels:
          app: zookeeper
          tier: zookeeper
      spec:
        containers:
        - envFrom:
          - configMapRef:
              name: hub-config
          image: blackducksoftware/hub-zookeeper:4.2.1
          name: zookeeper
          resources:
            requests:
              memory: 384M
            limits:
              memory: 384M
          volumes:
          - emptyDir: {}
            name: dir-1
            volumeMounts:
            - mountPath: "/opt/blackduck/hub/logs"
              name: dir-1
- apiVersion: v1
  kind: Service
  metadata:
    name: zookeeper
  spec:
    ports:
    - name: 2181-tcp
      port: 2181
      targetPort: 2181
    selector:
      app: zookeeper
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    name: nginx-webapp-logstash
  spec:
    ports:
    - name: 443-tcp
      port: 443
      targetPort: 8443
    selector:
      app: nginx-webapp-logstash
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    name: webapp
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      targetPort: 8080
    selector:
      app: nginx-webapp-logstash
  status:
    loadBalancer: {}
# Important to expose logstash for writing to logs.  maybe for reading as well .
- apiVersion: v1
  kind: Service
  metadata:
    name: logstash
  spec:
    ports:
    - name: 4560-tcp
      port: 4560
      targetPort: 4560
    - name: 5044-tcp-filebeat
      port: 5044
      targetPort: 5044
    selector:
      app: nginx-webapp-logstash
- apiVersion: v1
  kind: Service
  metadata:
    name: solr
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      targetPort: 8080
    selector:
      app: solr

- apiVersion: v1
  kind: Service
  metadata:
    name: registration
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      targetPort: 8080
    selector:
      app: registration

- apiVersion: v1
  kind: Service
  metadata:
    name: documentation
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      targetPort: 8080
    selector:
      app: documentation
